### ISSUE TITLE
checker-framework.groovy (generate): false differences when run locally

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12230]
When I run `groovy .ci/checker-framework.groovy checker-framework-nullness-optional-interning -g` locally on a clean master, I get the following differences (trimmed due to size) when I don't expect any:
````
diff --git a/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml b/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
index 775628e..292dbf7 100644
--- a/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
+++ b/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
@@ -1,6 +1,2499 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <suppressedErrors>
   <checkerFrameworkError unstable="false">
+    <fileName>checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\Checker.java</fileName>
+    <specifier>argument</specifier>
+    <message>incompatible argument for parameter moduleId of Violation.</message>
+    <lineContent>new String[] {ioe.getMessage()}, null, getClass(), null));</lineContent>
+    <details>
+      found   : null (NullType)
+    </details>
+  </checkerFrameworkError>
+
+  <checkerFrameworkError unstable="false">
+    <fileName>checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\Checker.java</fileName>
+    <specifier>method.invocation</specifier>
+    <message>call to addListener(com.puppycrawl.tools.checkstyle.api.AuditListener) not allowed on the given receiver.</message>
+    <lineContent>addListener(counter);</lineContent>
+    <details>
+      found   : @UnderInitialization(com.puppycrawl.tools.checkstyle.api.AutomaticBean.class) @NonNull Checker
+    </details>
+  </checkerFrameworkError>
+
....
 
@@ -5660,10 +8129,10 @@
     <fileName>checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java</fileName>
     <specifier>return</specifier>
     <message>incompatible types in return.</message>
-    <lineContent>return uri;</lineContent>
+    <lineContent>return CommonUtil.class.getResource(name);</lineContent>
     <details>
-      type of expression: @Initialized @Nullable URI
-      method return type: @Initialized @NonNull URI
+      type of expression: @Initialized @Nullable URL
+      method return type: @Initialized @NonNull URL
     </details>
   </checkerFrameworkError>
````

I am on a Windows machine.
This is making completing changes in my PRs complex.

**Comment by rnveach** [comment]
I expanding these differences also to my linux machine.

````
diff --git a/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml b/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
index 830a67b..d90dfe1 100644
--- a/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
+++ b/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
@@ -17,7 +5955,7 @@
     <message>incompatible argument for parameter customMessage of Violation.</message>
     <lineContent>new String[] {ioe.getMessage()}, null, getClass(), null));</lineContent>
     <details>
-      found   : null (NullType)
+      found  : null (NullType)
       required: @Initialized @NonNull String
     </details>
   </checkerFrameworkError>
@@ -28,7 +5966,7 @@
     <message>incompatible argument for parameter customMessage of Violation.</message>
     <lineContent>null, getClass(), null));</lineContent>
     <details>
-      found   : null (NullType)
+      found  : null (NullType)
       required: @Initialized @NonNull String
     </details>
   </checkerFrameworkError>
@@ -39,7 +5977,7 @@
     <message>incompatible argument for parameter moduleId of Violation.</message>
     <lineContent>new String[] {ioe.getMessage()}, null, getClass(), null));</lineContent>
     <details>
-      found   : null (NullType)
+      found  : null (NullType)
       required: @Initialized @NonNull String
     </details>
   </checkerFrameworkError>
@@ -50,7 +5988,7 @@
     <message>incompatible argument for parameter moduleId of Violation.</message>
     <lineContent>null, getClass(), null));</lineContent>
     <details>
-      found   : null (NullType)
+      found  : null (NullType)
       required: @Initialized @NonNull String
     </details>
   </checkerFrameworkError>
@@ -61,7 +5999,7 @@
     <message>incompatible types in assignment.</message>
     <lineContent>fileExtensions = null;</lineContent>
     <details>
-      found   : null (NullType)
+      found  : null (NullType)
       required: @Initialized @NonNull String @Initialized @NonNull []
     </details>
   </checkerFrameworkError>
@@ -79,7 +6017,7 @@
     <message>call to addListener(com.puppycrawl.tools.checkstyle.api.AuditListener) not allowed on the given receiver.</message>
     <lineContent>addListener(counter);</lineContent>
     <details>
-      found   : @UnderInitialization(com.puppycrawl.tools.checkstyle.api.AutomaticBean.class) @NonNull Checker
+      found  : @UnderInitialization(com.puppycrawl.tools.checkstyle.api.AutomaticBean.class) @NonNull Checker
       required: @Initialized @NonNull Checker
     </details>
   </checkerFrameworkError>
@@ -90,7 +6028,7 @@
     <message>incompatible argument for parameter arg0 of add.</message>
     <lineContent>fragments.add(null);</lineContent>
     <details>
-      found   : null (NullType)
+      found  : null (NullType)
       required: @Initialized @NonNull String
     </details>
   </checkerFrameworkError>
@@ -178,13 +6116,13 @@
   </checkerFrameworkError>
 
   <checkerFrameworkError unstable="false">
-    <fileName>checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/LocalizedMessage.java</fileName>
+    <fileName>checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java</fileName>
     <specifier>assignment</specifier>
     <message>incompatible types in assignment.</message>
-    <lineContent>this.args = null;</lineContent>
+    <lineContent>prevParent.branchTokenTypes = null;</lineContent>
     <details>
-      found   : null (NullType)
-      required: @Initialized @NonNull Object @Initialized @NonNull []
+      found  : null (NullType)
+      required: @Initialized @NonNull BitSet
     </details>
   </checkerFrameworkError>
 
@@ -270,10 +6197,10 @@
     <fileName>checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java</fileName>
     <specifier>return</specifier>
     <message>incompatible types in return.</message>
-    <lineContent>return returnList;</lineContent>
+    <lineContent>return returnValue;</lineContent>
     <details>
-      type of expression: @Initialized @Nullable List&lt;@Initialized @NonNull Token&gt;
-      method return type: @Initialized @NonNull List&lt;@Initialized @NonNull Token&gt;
+      type of expression: @Initialized @Nullable DetailAST
+      method return type: @Initialized @NonNull DetailAST
     </details>
   </checkerFrameworkError>
 
@@ -281,10 +6208,10 @@
     <fileName>checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java</fileName>
     <specifier>return</specifier>
     <message>incompatible types in return.</message>
-    <lineContent>return returnValue;</lineContent>
+    <lineContent>return returnList;</lineContent>
     <details>
-      type of expression: @Initialized @Nullable DetailAST
-      method return type: @Initialized @NonNull DetailAST
+      type of expression: @Initialized @Nullable List&lt;@Initialized @NonNull Token&gt;
+      method return type: @Initialized @NonNull List&lt;@Initialized @NonNull Token&gt;
     </details>
   </checkerFrameworkError>
 
@@ -294,7 +6221,7 @@
     <message>incompatible argument for parameter customMessage of Violation.</message>
     <lineContent>null);</lineContent>
     <details>
-      found   : null (NullType)
+      found  : null (NullType)
       required: @Initialized @NonNull String
     </details>
   </checkerFrameworkError>
....
````

**Comment by romani** [comment]
@rnveach , is this still an issue ? Strange that me and CI doesn't able to reproduce this.

**Comment by rnveach** [comment]
Windows, which is what this issue was originally for, is a confirmed issue with how we are parsing the output from the maven command. The output is different between Windows and Linux that we only programmed it for the Linux output. I made comments on how I think we should fix it but I believe we are waiting for the utility to figure it out.

Linux is oddly not reporting it as an issue anymore. 
````
$ groovy .ci/checker-framework.groovy checker-framework-nullness-optional-interning
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17:52 min
[INFO] Finished at: 2022-10-17T13:08:42-04:00
[INFO] ------------------------------------------------------------------------
Build successful with no errors.

$ git diff
$ 
````

**Comment by romani** [comment]
@rnveach , please close this issue and let's keep/open issue on windows support.

**Comment by rnveach** [comment]
@romani Just to confirm, your referring to #12221 for Windows support?

**Comment by romani** [comment]
Ok, please close this issue, or confirm that is still a problem after recent changes.
